version: '3.4'

services:
  alexsidebar2api:
    image: deanxv/alexsidebar2api:latest
    container_name: alexsidebar2api
    restart: always
    ports:
      - "10033:10033"
    volumes:
      - ./data:/app/alexsidebar2api/data
    environment:
      - AS_COOKIE=******  # cookie (多个请以,分隔)
      - API_SECRET=123456  # [可选]接口密钥-修改此行为请求头校验的值(多个请以,分隔)
      - TZ=Asia/Shanghai